import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Rubik,
  Merriweather,
  Inconsolata,
} from "next/font/google";
import "./globals.css";
import Dock from "@/components/Dock";
import navData from "@/data/navData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rubik = Rubik({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-rubik",
});

const merriweather = Merriweather({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-merriweather",
});

const inconsolata = Inconsolata({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-inconsolata",
});

export const metadata: Metadata = {
  title: "Marina Eleshaa | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const items = navData();  // بيانات فقط بدون JSX أو onClick

  return (
    <html lang="en" className={rubik.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rubik.variable} antialiased bg-black`}
      >
        <div className="relative min-h-screen">
          {children}

          <div className="fixed bottom-5 left-1/2 transform -translate-x-1/2">
            <Dock
              items={items}
              panelHeight={68}
              baseItemSize={50}
              magnification={70}
              className="text-white"
            />
          </div>
        </div>
      </body>
    </html>
  );
}
